### ISSUE TITLE
Installation ignores NAPI version for given electron

### ISSUE THREAD

**Issue by MasterOdin** [TryGhost/node-sqlite3#1598]
### Issue Summary

When upgrading from 4.2.0 to 5.0.6, I'm running into an issue where it's compiling the sqlite module to the wrong NAPI version. Currently, we set in our `.yarnrc` the following:
```
arch x64
disturl "https://electronjs.org/headers"
fallback_to_build "true"
lastUpdateCheck 1627935942343
runtime electron
target "9.4.4"
target_arch x64
```
and that would install the module for the right ABI for the given electron. Now, it seems like it's just always using our environment's node version (16) to choose the NAPI version (6), which then breaks for electron (which needs 3?).

Not sure if there's some new incantation that's necessary to get things to work for sqlite3, or if this is an upstream bug on node-pre-gyp?

### Relevant logs or output

After installing the module, and then starting electron:
```
Error: Cannot find module /redacted/node_modules/sqlite3/lib/binding/napi-v3-darwin-unknown-x64/node_sqlite3.node'
```

But I do have `node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node` installed.

### Version

5.0.6

### Node.js Version

16

### How did you install the library?

yarn, macOS, for electron 9.4.4
