### ISSUE TITLE
Cannot build/compile using electron-rebuild, node-addon-api errors

### ISSUE THREAD

**Issue by aramando** [TryGhost/node-sqlite3#1487]
I'm unable to build sqlite3 v5.0.2 using `electron-rebuild`, as you can see from the below console output there are a large number of errors from the `node-addon-api` module that sqlite3 was refactored to make use of from v5.

As a test I tried installing `bcrypt` as another example of a native module with a dependency that currently resolves to the same version of `node-addon-api` (v3.2.1, current) and it worked fine.

Ubuntu 20.04.2
electron-rebuild: 3.1.1 (current)
node-gyp: 8.1.0 (current)
electron: 8.2.5 (latest compatible with sqlite3)

```
⠋ Building module: sqlite3, Completed: 1gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/aramando/Projects/bs-package-upgrades/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aramando/Projects/bs-package-upgrades/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aramando/Projects/bs-package-upgrades/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aramando/.electron-gyp/8.2.5/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/aramando/.electron-gyp/8.2.5',
gyp info spawn args   '-Dnode_gyp_dir=/home/aramando/Projects/bs-package-upgrades/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/aramando/.electron-gyp/8.2.5/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/aramando/Projects/bs-package-upgrades/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
⠼ Building module: sqlite3, Completed: 1gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/aramando/Projects/bs-package-upgrades/node_modules/sqlite3/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
⠴ Building module: sqlite3, Completed: 1  COPY Release/nothing.a
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c
⠦ Building module: sqlite3, Completed: 1  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3340000/sqlite3.o
⠼ Building module: sqlite3, Completed: 1Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c: In function ‘cellArea’:
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190977:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
190977 |       case 5:  area  = p->aCoord[9].f - p->aCoord[8].f;
       |                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190978:7: note: here
190978 |       case 4:  area *= p->aCoord[7].f - p->aCoord[6].f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190978:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
190978 |       case 4:  area *= p->aCoord[7].f - p->aCoord[6].f;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190979:7: note: here
190979 |       case 3:  area *= p->aCoord[5].f - p->aCoord[4].f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190979:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
190979 |       case 3:  area *= p->aCoord[5].f - p->aCoord[4].f;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190980:7: note: here
190980 |       case 2:  area *= p->aCoord[3].f - p->aCoord[2].f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190980:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
190980 |       case 2:  area *= p->aCoord[3].f - p->aCoord[2].f;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190981:7: note: here
190981 |       default: area *= p->aCoord[1].f - p->aCoord[0].f;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190987:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
190987 |       case 5:  area  = (i64)p->aCoord[9].i - (i64)p->aCoord[8].i;
       |                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190988:7: note: here
190988 |       case 4:  area *= (i64)p->aCoord[7].i - (i64)p->aCoord[6].i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190988:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
190988 |       case 4:  area *= (i64)p->aCoord[7].i - (i64)p->aCoord[6].i;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190989:7: note: here
190989 |       case 3:  area *= (i64)p->aCoord[5].i - (i64)p->aCoord[4].i;
       |       ^~~~
⠴ Building module: sqlite3, Completed: 1Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190989:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
190989 |       case 3:  area *= (i64)p->aCoord[5].i - (i64)p->aCoord[4].i;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190990:7: note: here
190990 |       case 2:  area *= (i64)p->aCoord[3].i - (i64)p->aCoord[2].i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190990:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
190990 |       case 2:  area *= (i64)p->aCoord[3].i - (i64)p->aCoord[2].i;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190991:7: note: here
190991 |       default: area *= (i64)p->aCoord[1].i - (i64)p->aCoord[0].i;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c: In function ‘rtreeCallbackConstraint’:
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190130:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190130 |                 readCoord(pCellData+32, &c); aCoord[8] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190131:7: note: here
190131 |       case 8:   readCoord(pCellData+28, &c); aCoord[7] = c.f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190132:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190132 |                 readCoord(pCellData+24, &c); aCoord[6] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190133:7: note: here
190133 |       case 6:   readCoord(pCellData+20, &c); aCoord[5] = c.f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190134:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190134 |                 readCoord(pCellData+16, &c); aCoord[4] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190135:7: note: here
190135 |       case 4:   readCoord(pCellData+12, &c); aCoord[3] = c.f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190136:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190136 |                 readCoord(pCellData+8,  &c); aCoord[2] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190137:7: note: here
190137 |       default:  readCoord(pCellData+4,  &c); aCoord[1] = c.f;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190145:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190145 |                 readCoord(pCellData+32, &c); aCoord[8] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190146:7: note: here
190146 |       case 8:   readCoord(pCellData+28, &c); aCoord[7] = c.i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190147:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190147 |                 readCoord(pCellData+24, &c); aCoord[6] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190148:7: note: here
190148 |       case 6:   readCoord(pCellData+20, &c); aCoord[5] = c.i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190149:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190149 |                 readCoord(pCellData+16, &c); aCoord[4] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190150:7: note: here
190150 |       case 4:   readCoord(pCellData+12, &c); aCoord[3] = c.i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190151:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190151 |                 readCoord(pCellData+8,  &c); aCoord[2] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190152:7: note: here
190152 |       default:  readCoord(pCellData+4,  &c); aCoord[1] = c.i;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c: In function ‘rtreeNonleafConstraint’:
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190207:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
190207 |       if( p->op!=RTREE_EQ ) break;  /* RTREE_LE and RTREE_LT end here */
       |         ^
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190210:5: note: here
190210 |     default: /* RTREE_GT or RTREE_GE,  or fallthrough of RTREE_EQ */
       |     ^~~~~~~
⠸ Building module: sqlite3, Completed: 1  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/backup.o
⠦ Building module: sqlite3, Completed: 1In file included from /home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi.h:2725,
                 from ../src/backup.cc:2:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In member function ‘T* Napi::Env::GetInstanceData()’:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:471:24: error: there are no arguments to ‘napi_get_instance_data’ that depend on a template parameter, so a declaration of ‘napi_get_instance_data’ must be available [-fpermissive]
  471 |   napi_status status = napi_get_instance_data(_env, &data);
      |                        ^~~~~~~~~~~~~~~~~~~~~~
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:471:24: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In static member function ‘static Napi::BigInt Napi::BigInt::New(napi_env, int64_t)’:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:793:24: error: ‘napi_create_bigint_int64’ was not declared in this scope; did you mean ‘napi_create_int64’?
  793 |   napi_status status = napi_create_bigint_int64(env, val, &value);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~
      |                        napi_create_int64
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In static member function ‘static Napi::BigInt Napi::BigInt::New(napi_env, uint64_t)’:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:800:24: error: ‘napi_create_bigint_uint64’ was not declared in this scope; did you mean ‘napi_create_string_utf16’?
  800 |   napi_status status = napi_create_bigint_uint64(env, val, &value);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                        napi_create_string_utf16
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In static member function ‘static Napi::BigInt Napi::BigInt::New(napi_env, int, size_t, const uint64_t*)’:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:807:24: error: ‘napi_create_bigint_words’ was not declared in this scope; did you mean ‘napi_create_async_work’?
  807 |   napi_status status = napi_create_bigint_words(env, sign_bit, word_count, words, &value);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~
      |                        napi_create_async_work
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In member function ‘int64_t Napi::BigInt::Int64Value(bool*) const’:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:820:24: error: ‘napi_get_value_bigint_int64’ was not declared in this scope; did you mean ‘napi_get_value_int64’?
  820 |   napi_status status = napi_get_value_bigint_int64(
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        napi_get_value_int64
⠧ Building module: sqlite3, Completed: 1/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In member function ‘uint64_t Napi::BigInt::Uint64Value(bool*) const’:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:828:24: error: ‘napi_get_value_bigint_uint64’ was not declared in this scope; did you mean ‘napi_get_value_string_utf16’?
  828 |   napi_status status = napi_get_value_bigint_uint64(
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        napi_get_value_string_utf16
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In member function ‘size_t Napi::BigInt::WordCount() const’:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:836:24: error: ‘napi_get_value_bigint_words’ was not declared in this scope; did you mean ‘napi_get_value_string_utf16’?
  836 |   napi_status status = napi_get_value_bigint_words(
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        napi_get_value_string_utf16
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In member function ‘void Napi::BigInt::ToWords(int*, size_t*, uint64_t*)’:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:843:24: error: ‘napi_get_value_bigint_words’ was not declared in this scope; did you mean ‘napi_get_value_string_utf16’?
  843 |   napi_status status = napi_get_value_bigint_words(
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        napi_get_value_string_utf16
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In member function ‘bool Napi::Object::Freeze()’:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:1393:24: error: ‘napi_object_freeze’ was not declared in this scope; did you mean ‘napi_object_expected’?
 1393 |   napi_status status = napi_object_freeze(_env, _value);
      |                        ^~~~~~~~~~~~~~~~~~
      |                        napi_object_expected
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In member function ‘bool Napi::Object::Seal()’:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:1399:24: error: ‘napi_object_seal’ was not declared in this scope; did you mean ‘napi_object’?
 1399 |   napi_status status = napi_object_seal(_env, _value);
      |                        ^~~~~~~~~~~~~~~~
      |                        napi_object
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In member function ‘bool Napi::ArrayBuffer::IsDetached() const’:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:1606:24: error: ‘napi_is_detached_arraybuffer’ was not declared in this scope; did you mean ‘napi_create_arraybuffer’?
 1606 |   napi_status status = napi_is_detached_arraybuffer(_env, _value, &detached);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        napi_create_arraybuffer
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In member function ‘void Napi::ArrayBuffer::Detach()’:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:1612:24: error: ‘napi_detach_arraybuffer’ was not declared in this scope; did you mean ‘napi_create_arraybuffer’?
 1612 |   napi_status status = napi_detach_arraybuffer(_env, _value);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~
      |                        napi_create_arraybuffer
⠇ Building module: sqlite3, Completed: 1../src/backup.cc: In static member function ‘static void node_sqlite3::Backup::Work_BeginInitialize(node_sqlite3::Database::Baton*)’:
../src/backup.cc:179:9: warning: unused variable ‘status’ [-Wunused-variable]
  179 |     int status = napi_create_async_work(
      |         ^~~~~~
In file included from ../src/backup.cc:4:
../src/backup.cc: In static member function ‘static void node_sqlite3::Backup::Work_BeginStep(node_sqlite3::Backup::Baton*)’:
../src/macros.h:182:9: warning: unused variable ‘status’ [-Wunused-variable]
  182 |     int status = napi_create_async_work(                                       \
      |         ^~~~~~
../src/backup.cc:252:5: note: in expansion of macro ‘BACKUP_BEGIN’
  252 |     BACKUP_BEGIN(Step);
      |     ^~~~~~~~~~~~
⠏ Building module: sqlite3, Completed: 1../src/backup.cc: In static member function ‘static void node_sqlite3::Backup::Work_BeginFinish(node_sqlite3::Backup::Baton*)’:
../src/macros.h:182:9: warning: unused variable ‘status’ [-Wunused-variable]
  182 |     int status = napi_create_async_work(                                       \
      |         ^~~~~~
../src/backup.cc:319:5: note: in expansion of macro ‘BACKUP_BEGIN’
  319 |     BACKUP_BEGIN(Finish);
      |     ^~~~~~~~~~~~
In file included from /home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi.h:2725,
                 from ../src/backup.cc:2:
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h: In instantiation of ‘T* Napi::Env::GetInstanceData() [with T = Napi::FunctionReference]’:
../src/database.h:38:58:   required from here
/home/aramando/Projects/bs-package-upgrades/node_modules/node-addon-api/napi-inl.h:471:46: error: ‘napi_get_instance_data’ was not declared in this scope; did you mean ‘napi_new_instance’?
  471 |   napi_status status = napi_get_instance_data(_env, &data);
      |                        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
      |                        napi_new_instance
⠋ Building module: sqlite3, Completed: 1make: *** [node_sqlite3.target.mk:136: Release/obj.target/node_sqlite3/src/backup.o] Error 1
make: Leaving directory '/home/aramando/Projects/bs-package-upgrades/node_modules/sqlite3/build'
✖ Rebuild Failed

```

**Comment by aramando** [comment]
Incidentally I have had a colleague recreate the errors and also verified that the same thing happens in our test runner Docker image. I notice that in issue #1467 they report that the build worked OK with node-addon-api@3.1.0 so it doesn't seem to be a uni

**Comment by clementlize** [comment]
Same output here. @aramando did you manage to solve this problem?

**Comment by aramando** [comment]
> Same output here. @aramando did you manage to solve this problem?

Sadly not.

**Comment by clementlize** [comment]
After asking on the electron Discord, someone told me to pin _node-addon-api_ to a less recent version. No more details, I will try and give you updates.

**Comment by clementlize** [comment]
Someone in the electron discord server suggested to pin the version of _node-addon-api_.

I tried several versions without success. Then I looked in _node_modules/sqlite3/package.json_ and saw this dependency: `"node-addon-api": "^3.0.0",`

So I pinned node-addon-api to v3.0.0 and it worked, **no errors**!

---

:heavy_check_mark:  How to solve : 

1. Edit your _package.json_ file and add `"resolutions": { "node-addon-api": "3.0.0" }` below _dependencies_ or _devDependencies_ for example.

2. Run `yarn install`
You should probably see warnings like this: `warning Resolution field "node-addon-api@3.0.0" is incompatible with requested version "node-addon-api@<<x.x.x>>"`

3. Then run the `electron-rebuild` command and everything should be fine

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂

**Comment by Mumbaso21** [comment]
@clementlize has right.
I add another tip if you have multiple packages that has the same error and you need the use different versions of `node-addon-api`. Instead of using:
`"resolutions": { "node-addon-api": "3.0.0" }`
that changes the version for all packages, you can use:
`"resolutions": { "[package-name]/node-addon-api": "3.0.0" }`
this will change the dependency only for the package `package-name` (without square brackets).
In my case `argon2` version 0.30.x causing the issue, solved with:
`"resolutions": { "argon2/node-addon-api": "3.0.0" }`

Hope this helps.
