### ISSUE TITLE
3.1.1 seems to not work with node 4

### ISSUE THREAD

**Issue by tjwebb** [TryGhost/node-sqlite3#581]
> The sqlite3 module works with Node.js v0.10.x, v0.12.x, v4.x, and v5.x.

I can't get any single version of sqlite3 to work with both node 4 and node 5. Is this a known issue?

**Comment by hoichong** [comment]
I have the same issue, node-sqlite3 does not work with Node v4.2.4

**Comment by shotor** [comment]
I have a similar issue when trying to use Knex 0.8/0.9 with Sqlite3 3.1.1:

```
31mKnex: run
$ npm install sqlite3 --save
Error: Cannot find module '/home/shotor/Projects/playground/electron-react-boilerplate/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node'
```
Any idea how to get this v47 binding?

**Comment by laispace** [comment]
@shotor Try sudo:
```
sudo npm install sqlite3
```
It works for me.(node@4.2.4 and sqlite3@3.1.1)

**Comment by shotor** [comment]
@laispace Thanks, but no dice unfortunately. Still only see a v46 version.

**Comment by zzolo** [comment]
I am having the same issue.

**Comment by daniellockyer** [comment]
Please try with newer versions of `node-sqlite3` 🙂
