### ISSUE TITLE
Compilation error with node-addon-api 3.2.0

### ISSUE THREAD

**Issue by senotrusov** [TryGhost/node-sqlite3#1467]
Hello!

Just a few days ago ``node-addon-api 3.2.0`` came out. I tried to compile ``node-sqlite3 5.0.2`` with ``node-addon-api 3.2.0`` and the compilation fails.

Previously, ``node-sqlite3 5.0.2`` builds well with ``node-addon-api 3.1.0``, so I guess something is changed in ``node-addon-api 3.2.0`` that breaks the build.

On ``Ubuntu 20.04 64bit`` I got the following error:

```
- Preparing native dependencies
make: Entering directory '/tmp/electron-packager/linux-x64/hello-linux-x64/resources/app/node_modules/sqlite3/build'
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  AR(target) Release/obj.target/node_modules/node-addon-api/nothing.a
  COPY Release/nothing.a
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3340000/sqlite3.o
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c: In function ‘cellArea’:
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190977:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
190977 |       case 5:  area  = p->aCoord[9].f - p->aCoord[8].f;
       |                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190978:7: note: here
190978 |       case 4:  area *= p->aCoord[7].f - p->aCoord[6].f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190978:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
190978 |       case 4:  area *= p->aCoord[7].f - p->aCoord[6].f;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190979:7: note: here
190979 |       case 3:  area *= p->aCoord[5].f - p->aCoord[4].f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190979:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
190979 |       case 3:  area *= p->aCoord[5].f - p->aCoord[4].f;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190980:7: note: here
190980 |       case 2:  area *= p->aCoord[3].f - p->aCoord[2].f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190980:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
190980 |       case 2:  area *= p->aCoord[3].f - p->aCoord[2].f;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190981:7: note: here
190981 |       default: area *= p->aCoord[1].f - p->aCoord[0].f;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190987:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
190987 |       case 5:  area  = (i64)p->aCoord[9].i - (i64)p->aCoord[8].i;
       |                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190988:7: note: here
190988 |       case 4:  area *= (i64)p->aCoord[7].i - (i64)p->aCoord[6].i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190988:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
190988 |       case 4:  area *= (i64)p->aCoord[7].i - (i64)p->aCoord[6].i;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190989:7: note: here
190989 |       case 3:  area *= (i64)p->aCoord[5].i - (i64)p->aCoord[4].i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190989:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
190989 |       case 3:  area *= (i64)p->aCoord[5].i - (i64)p->aCoord[4].i;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190990:7: note: here
190990 |       case 2:  area *= (i64)p->aCoord[3].i - (i64)p->aCoord[2].i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190990:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
190990 |       case 2:  area *= (i64)p->aCoord[3].i - (i64)p->aCoord[2].i;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190991:7: note: here
190991 |       default: area *= (i64)p->aCoord[1].i - (i64)p->aCoord[0].i;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c: In function ‘rtreeCallbackConstraint’:
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190130:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190130 |                 readCoord(pCellData+32, &c); aCoord[8] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190131:7: note: here
190131 |       case 8:   readCoord(pCellData+28, &c); aCoord[7] = c.f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190132:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190132 |                 readCoord(pCellData+24, &c); aCoord[6] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190133:7: note: here
190133 |       case 6:   readCoord(pCellData+20, &c); aCoord[5] = c.f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190134:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190134 |                 readCoord(pCellData+16, &c); aCoord[4] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190135:7: note: here
190135 |       case 4:   readCoord(pCellData+12, &c); aCoord[3] = c.f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190136:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190136 |                 readCoord(pCellData+8,  &c); aCoord[2] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190137:7: note: here
190137 |       default:  readCoord(pCellData+4,  &c); aCoord[1] = c.f;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190145:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190145 |                 readCoord(pCellData+32, &c); aCoord[8] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190146:7: note: here
190146 |       case 8:   readCoord(pCellData+28, &c); aCoord[7] = c.i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190147:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190147 |                 readCoord(pCellData+24, &c); aCoord[6] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190148:7: note: here
190148 |       case 6:   readCoord(pCellData+20, &c); aCoord[5] = c.i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190149:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190149 |                 readCoord(pCellData+16, &c); aCoord[4] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190150:7: note: here
190150 |       case 4:   readCoord(pCellData+12, &c); aCoord[3] = c.i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190151:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
190151 |                 readCoord(pCellData+8,  &c); aCoord[2] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190152:7: note: here
190152 |       default:  readCoord(pCellData+4,  &c); aCoord[1] = c.i;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c: In function ‘rtreeNonleafConstraint’:
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190207:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
190207 |       if( p->op!=RTREE_EQ ) break;  /* RTREE_LE and RTREE_LT end here */
       |         ^
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190210:5: note: here
190210 |     default: /* RTREE_GT or RTREE_GE,  or fallthrough of RTREE_EQ */
       |     ^~~~~~~
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/backup.o
In file included from /tmp/electron-packager/linux-x64/hello-linux-x64/resources/app/node_modules/sqlite3/node_modules/node-addon-api/napi.h:2725,
                 from ../src/backup.cc:2:
/tmp/electron-packager/linux-x64/hello-linux-x64/resources/app/node_modules/sqlite3/node_modules/node-addon-api/napi-inl.h: In member function ‘bool Napi::Object::Freeze()’:
/tmp/electron-packager/linux-x64/hello-linux-x64/resources/app/node_modules/sqlite3/node_modules/node-addon-api/napi-inl.h:1393:24: error: ‘napi_object_freeze’ was not declared in this scope; did you mean ‘napi_object_expected’?
 1393 |   napi_status status = napi_object_freeze(_env, _value);
      |                        ^~~~~~~~~~~~~~~~~~
      |                        napi_object_expected
/tmp/electron-packager/linux-x64/hello-linux-x64/resources/app/node_modules/sqlite3/node_modules/node-addon-api/napi-inl.h: In member function ‘bool Napi::Object::Seal()’:
/tmp/electron-packager/linux-x64/hello-linux-x64/resources/app/node_modules/sqlite3/node_modules/node-addon-api/napi-inl.h:1399:24: error: ‘napi_object_seal’ was not declared in this scope; did you mean ‘napi_object’?
 1399 |   napi_status status = napi_object_seal(_env, _value);
      |                        ^~~~~~~~~~~~~~~~
      |                        napi_object
../src/backup.cc: In static member function ‘static void node_sqlite3::Backup::Work_BeginInitialize(node_sqlite3::Database::Baton*)’:
../src/backup.cc:179:9: warning: unused variable ‘status’ [-Wunused-variable]
  179 |     int status = napi_create_async_work(
      |         ^~~~~~
In file included from ../src/backup.cc:4:
../src/backup.cc: In static member function ‘static void node_sqlite3::Backup::Work_BeginStep(node_sqlite3::Backup::Baton*)’:
../src/macros.h:182:9: warning: unused variable ‘status’ [-Wunused-variable]
  182 |     int status = napi_create_async_work(                                       \
      |         ^~~~~~
../src/backup.cc:252:5: note: in expansion of macro ‘BACKUP_BEGIN’
  252 |     BACKUP_BEGIN(Step);
      |     ^~~~~~~~~~~~
../src/backup.cc: In static member function ‘static void node_sqlite3::Backup::Work_BeginFinish(node_sqlite3::Backup::Baton*)’:
../src/macros.h:182:9: warning: unused variable ‘status’ [-Wunused-variable]
  182 |     int status = napi_create_async_work(                                       \
      |         ^~~~~~
../src/backup.cc:319:5: note: in expansion of macro ‘BACKUP_BEGIN’
  319 |     BACKUP_BEGIN(Finish);
      |     ^~~~~~~~~~~~
make: *** [node_sqlite3.target.mk:144: Release/obj.target/node_sqlite3/src/backup.o] Error 1
make: Leaving directory '/tmp/electron-packager/linux-x64/hello-linux-x64/resources/app/node_modules/sqlite3/build'
✖ Preparing native dependencies: 0 / 1

An unhandled error has occurred inside Forge:
node-gyp failed to rebuild '/tmp/electron-packager/linux-x64/hello-linux-x64/resources/app/node_modules/sqlite3'.
Error: `make` failed with exit code: 2


Error: node-gyp failed to rebuild '/tmp/electron-packager/linux-x64/hello-linux-x64/resources/app/node_modules/sqlite3'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/home/runner/work/desktop/desktop/node_modules/electron-rebuild/src/module-rebuilder.ts:231:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Rebuilder.rebuildModuleAt (/home/runner/work/desktop/desktop/node_modules/electron-rebuild/src/rebuild.ts:283:5)
    at Rebuilder.rebuild (/home/runner/work/desktop/desktop/node_modules/electron-rebuild/src/rebuild.ts:189:9)
    at /home/runner/work/desktop/desktop/node_modules/@electron-forge/core/src/util/rebuild.ts:33:5
```

As a workaround, I fixed the ``node-addon-api`` version for my build using ``npm-force-resolutions``
```
  "scripts": {
    "preinstall": "npx npm-force-resolutions",
  },
  "resolutions": {
    "node-addon-api": "3.1.0"
  },
```

Thank you!
