### ISSUE TITLE
Cannot compile on Windows 10 against latest nwjs (0.39.1)

### ISSUE THREAD

**Issue by theDevelopper** [TryGhost/node-sqlite3#1179]
Hi, 

I am trying to compile sqlite3 against the latest version 0.39.1 of nwjs (node-webkit). 
It works fine on macOS but not on Windows 10. It worked fine with nwjs 0.37.4

I tried sqlite3 4.0.8 and 4.0.9

node-pre-gyp, node-gyp and nw-gyp are on the latest version. 

I get the following error: LNK2019

output:

```
  ..\src\statement.cc(153): note: see reference to function template instantiation 'void node_sqlite3::Statement::Error<node_sqlite3::Statement::PrepareBaton>(T *)' being compiled

          with

          [

              T=node_sqlite3::Statement::PrepareBaton

          ]

..\src\statement.cc(78): warning C4996: 'Nan::MakeCallback': was declared deprecated [C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\build\node_sqlite3.vcxproj]

  C:\Jenkins\workspace\tb_develop@2\dist\node_modules\nan\nan.h(959): note: see declaration of 'Nan::MakeCallback'

  win_delay_load_hook.cc

     Creating library C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\build\Release\node_sqlite3.lib and object C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\build\Release\node_sqlite3.exp

backup.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl v8::EscapableHandleScope::~EscapableHandleScope(void)" (__imp_??1EscapableHandleScope@v8@@QEAA@XZ) referenced in function "int `class v8::MaybeLocal<class v8::Value> __cdecl Nan::Get(class MaybeLocal<class v8::Value>::Local<class v8::Object>,unsigned int)'::`1'::dtor$0" (?dtor$0@?0??Get@Nan@@YA?AV?$MaybeLocal@VValue@v8@@@v8@@V?$Local@VObject@v8@@@3@I@Z@4HA) [C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\build\node_sqlite3.vcxproj]

database.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl v8::EscapableHandleScope::~EscapableHandleScope(void)" (__imp_??1EscapableHandleScope@v8@@QEAA@XZ) [C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\build\node_sqlite3.vcxproj]

node_sqlite3.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl v8::EscapableHandleScope::~EscapableHandleScope(void)" (__imp_??1EscapableHandleScope@v8@@QEAA@XZ) [C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\build\node_sqlite3.vcxproj]

statement.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl v8::EscapableHandleScope::~EscapableHandleScope(void)" (__imp_??1EscapableHandleScope@v8@@QEAA@XZ) [C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\build\node_sqlite3.vcxproj]

C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\build\Release\node_sqlite3.node : fatal error LNK1120: 1 unresolved externals [C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\build\node_sqlite3.vcxproj]

gyp ERR! build error 

gyp ERR! stack Error: `msbuild` failed with exit code: 1

gyp ERR! stack     at ChildProcess.onExit (C:\Users\bb\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:261:23)

gyp ERR! stack     at ChildProcess.emit (events.js:200:13)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

gyp ERR! System Windows_NT 10.0.17134

gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bb\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "build" "--build-from-source" "--directory=./node_modules/sqlite3" "--runtime=node-webkit" "--target_arch=x64" "--target=0.39.1" "--msvs_version=2015" "--module=C:\\Jenkins\\workspace\\tb_develop@2\\dist\\node_modules\\sqlite3\\lib\\binding\\node-webkit-v0.39.1-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Jenkins\\workspace\\tb_develop@2\\dist\\node_modules\\sqlite3\\lib\\binding\\node-webkit-v0.39.1-win32-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-webkit-v0.39.1"

gyp ERR! cwd C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3

gyp ERR! node -v v12.3.1

gyp ERR! nw-gyp -v v3.6.3

gyp ERR! not ok 

node-pre-gyp ERR! build error 

node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd build --build-from-source --directory=./node_modules/sqlite3 --runtime=node-webkit --target_arch=x64 --target=0.39.1 --msvs_version=2015 --module=C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\lib\binding\node-webkit-v0.39.1-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\lib\binding\node-webkit-v0.39.1-win32-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-webkit-v0.39.1' (1)

node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\bb\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\compile.js:83:29)

node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)

node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)

node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

node-pre-gyp ERR! System Windows_NT 10.0.17134

node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bb\\AppData\\Roaming\\npm\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--build-from-source" "--directory=./node_modules/sqlite3" "--runtime=node-webkit" "--target_arch=x64" "--target=0.39.1" "--msvs_version=2015"

node-pre-gyp ERR! cwd C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3

node-pre-gyp ERR! node -v v12.3.1

node-pre-gyp ERR! node-pre-gyp -v v0.13.0

node-pre-gyp ERR! not ok 

Failed to execute 'nw-gyp.cmd build --build-from-source --directory=./node_modules/sqlite3 --runtime=node-webkit --target_arch=x64 --target=0.39.1 --msvs_version=2015 --module=C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\lib\binding\node-webkit-v0.39.1-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Jenkins\workspace\tb_develop@2\dist\node_modules\sqlite3\lib\binding\node-webkit-v0.39.1-win32-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-webkit-v0.39.1' (1)

script returned exit code 1
```

**Comment by kewde** [comment]
Thank you for the bug report, I'm sorry to inform you that I don't know enough about compilation on Windows (nor do I have a Windows machine at my disposal) to test this out.

**Comment by panther7** [comment]
Same problem like @theDevelopper, any progress with fix?

**Comment by panther7** [comment]
Works on 0.37.4, 0.38.0-0.38.4

**Comment by panther7** [comment]
Doesn't works on Windows 7 too.

**Comment by panther7** [comment]
This issue could be closed, because all the thinks are solving here:       https://github.com/nwjs/nw-gyp/issues/130

**Comment by panther7** [comment]
ia32 build in clang is broken, check this issue https://github.com/nwjs/nw-gyp/issues/130#issuecomment-541680390

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
